### PR TITLE
Remove Dependency on InstallTrigger. Replacement is OnBeforeSendHeade…

### LINKED ISSUE #74: SAMLTracer.js Error in Firefox Developer Edition (103.0b2)
SAML-tracer appears to have stopped functioning in the latest Firefox Beta (Developer Edition tracks with Beta)

```
Uncaught Error: Type error for parameter extraInfoSpec (Error processing 2: Invalid enumeration value "extraHeaders") for webRequest.onBeforeSendHeaders.
    init moz-extension://21213b32-20d7-404e-b9f3-25e9c5930f22/src/SAMLTrace.js:943
    <anonymous> moz-extension://21213b32-20d7-404e-b9f3-25e9c5930f22/src/ui.js:15
[SAMLTrace.js:943:42](moz-extension://21213b32-20d7-404e-b9f3-25e9c5930f22/src/SAMLTrace.js)
    makeError resource://gre/modules/Schemas.jsm:539
    throwError resource://gre/modules/Schemas.jsm:2659
    fixedArgs resource://gre/modules/Schemas.jsm:2727
    map self-hosted:180
    checkParameters resource://gre/modules/Schemas.jsm:2720
    addStub resource://gre/modules/Schemas.jsm:2956
    init moz-extension://21213b32-20d7-404e-b9f3-25e9c5930f22/src/SAMLTrace.js:943
    <anonymous> moz-extension://21213b32-20d7-404e-b9f3-25e9c5930f22/src/ui.js:15
```

I've tried tried disabling all other extensions, etc. This occurs only with FF 103 insofar as I can tell... which will be the "main" version of Firefox come July 22. I don't know precisely that this is an issue with SAML-tracer vs. FF, though a cursory search on Bugzilla doesn't reflect anything related to changes/bugs with `webRequest.onBeforeSendHeaders`.

Screenshot:

Could any of the maintainers provide some insight? I typically use developer edition just so that I have a completely separate browser for debugging SAML (hate clearing cache on my main browser). I can work around this tentatively, but I'd hate to see FF103 drop in July and break SAML-Tracer.

### PR DESCRIPTION
**Pull request by kellenmurphy**
…rsOptions.EXTRA_HEADERS and OnHeadersReceivedOptions.EXTRA_HEADERS predefined constants.

This fixes #74, implementing Chrome-specific checks to predefined constants that return 'extraHeaders' for Chrome only, and are undefined for other browsers, which we can then filter.

### CODE REVIEW

File: src/SAMLTrace.js [hunk 1]
```diff
@@ -925,13 +913,13 @@ SAMLTrace.TraceWindow.init = function() {
   browser.webRequest.onBeforeSendHeaders.addListener(
     traceWindow.attachHeadersToRequest,
     {urls: ["<all_urls>"]},
-    getOnBeforeSendHeadersExtraInfoSpec()
+    ['blocking', 'requestHeaders', browser.webRequest.OnBeforeSendHeadersOptions.EXTRA_HEADERS].filter(Boolean)
   );
-
+
```
Comment (tvdijen) [inline src/SAMLTrace.js:918]: Stray space?

Comment (kellenmurphy) [reply src/SAMLTrace.js]: yep, my bad... fixed

**Comment by tvdijen** [comment]
@khlr Up to you to merge this.. It's just not my expertise

**Comment by khlr** [comment]
`filter(Boolean)` is a really smart idea. I like it 🙂👍

I'm just wondering if this will work in Firefox. I can't debug it right now. Did you already debug the change @kellenmurphy ?

I think there's a possible null reference when accessing the both `FooOptions.EXTRA_HEADERS` because the options objects only exist in chrome but not in Firefox?

**Comment by khlr** [comment]
Ah well, forgot what I said 😁 Accessing the options results in undefined if they don't exist. And undefined is falsy which means it will be just filtered out 👍
